# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  issues:
    types: [opened, closed]
  pull_request:
    branches:
      - master

jobs:
  deploy:
    env:
      GKEY: ${{ secrets.GKEY }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install opencv-python
          pip install smtp
          pip install pillow
          pip install numpy
      - name: Send Email
        run: |
          python actions/main.py

      # - uses: octokit/graphql-action@v2.x
      #   id: start_sending
      #   with:
      #     query: |
      #       query send($login:){
      #         user(login:$login){
      #             avatarUrl
      #           }
      #          }

      #    login: ${{ github.actor.login }}
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #    ORG: ${{ github.event.repository.owner.name }}

      - run: "echo 'latest release: ${{ github.event }}'"
